version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/IITH-SBJoshi/concurrency-decentralized-network
      
    steps:
      - checkout
      -run : sudo apt-get install libgtk-3-dev
      - run :
          name: gtk install
          command: |
            sudo apt-get install libgtk-3-dev
      - run : go get -u github.com/andlabs/ui
      - run: go get -u github.com/golang/lint/golint
      - run: go get -u github.com/GeertJohan/fgt
      - run:
         name: run tests
         command: |
           go test ./...